name: pbmorl
channels:
  - pytorch
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2020.1.1
  - cairo=1.14.12
  - certifi=2019.11.28
  - cpuonly=1.0
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - glib=2.63.1
  - graphite2=1.3.13
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2020.0
  - jasper=2.0.14
  - jpeg=9b
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.9
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.1
  - ninja=1.9.0
  - olefile=0.46
  - opencv=3.4.2
  - openssl=1.1.1h
  - patchelf=0.10
  - pcre=8.43
  - pip=20.0.2
  - pixman=0.38.0
  - py-opencv=3.4.2
  - python=3.7.6
  - readline=7.0
  - six=1.14.0
  - sqlite=3.31.1
  - tk=8.6.8
  - torchvision=0.5.0
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - about-time==4.2.1
    - absl-py==1.1.0
    - alive-progress==3.1.4
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - atari-py==0.2.9
    - attrs==21.4.0
    - autograd==1.6.2
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.0
    - bullet==2.2.0
    - cached-property==1.5.2
    - cffi==1.15.0
    - charset-normalizer==2.0.4
    - click==8.1.7
    - cloudpickle==1.2.2
    - cma==3.2.2
    - colorama==0.4.6
    - coloredlogs==15.0.1
    - colorlover==0.3.0
    - cufflinks==0.17.3
    - cvxpy==1.2.1
    - cycler==0.10.0
    - cython==0.29.22
    - d4rl==1.1
    - daemoniker==0.2.3
    - debugpy==1.6.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - deprecated==1.2.14
    - dill==0.3.7
    - dm-control==1.0.13
    - dm-env==1.6
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - ecos==2.0.10
    - entrypoints==0.4
    - evogym==1.0.0
    - farama-notifications==0.0.4
    - fasteners==0.16
    - fastjsonschema==2.15.3
    - filelock==3.12.2
    - fonttools==4.38.0
    - fsspec==2023.1.0
    - future==0.18.2
    - getch==1.0
    - gitdb==4.0.11
    - gitpython==3.1.40
    - glfw==2.5.0
    - gpy==1.10.0
    - gpyopt==1.2.6
    - grapheme==0.6.0
    - gym==0.22.0
    - gym-notices==0.0.7
    - gymnasium==0.28.1
    - h5py==3.6.0
    - hdbscan==0.8.28
    - huggingface-hub==0.16.4
    - humanfriendly==9.2
    - hvwfg==1.0.2
    - hyperopt==0.2.5
    - idna==3.2
    - imageio==2.14.1
    - importlib-metadata==4.11.4
    - importlib-resources==5.7.1
    - inflection==0.5.1
    - ipykernel==6.13.0
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.0
    - jax-jumpy==1.0.0
    - jedi==0.18.1
    - jinja2==3.0.1
    - joblib==1.1.0
    - jsonpatch==1.32
    - jsonpointer==2.3
    - jsonschema==4.6.0
    - jupyter-client==7.3.1
    - jupyter-core==4.10.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==1.1.0
    - kiwisolver==1.3.2
    - labmaze==1.0.6
    - lxml==4.6.3
    - markupsafe==2.0.1
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mjrl==1.0.0
    - mo-gymnasium==0.3.4
    - mpi4py==3.1.1
    - mujoco==2.3.6
    - mujoco-py==2.1.2.14
    - nbclient==0.6.4
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - neat-python==0.92
    - nest-asyncio==1.5.5
    - networkx==2.6.2
    - notebook==6.4.11
    - numpy==1.21.5
    - opencv-python==4.5.5.62
    - osqp==0.6.2.post5
    - packaging==21.3
    - pandas==1.3.2
    - pandocfilters==1.5.0
    - paramz==0.9.5
    - parso==0.8.3
    - pathtools==0.1.2
    - patsy==0.5.2
    - pettingzoo==1.19.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.0.0
    - plotly==5.8.0
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.29
    - protobuf==4.24.4
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pybind11==2.9.0
    - pybullet==3.2.5
    - pycparser==2.20
    - pygame==2.1.2
    - pygifsicle==1.0.5
    - pyglet==1.5.0
    - pygments==2.12.0
    - pymoo==0.6.0.1
    - pymunk==6.2.1
    - pyopengl==3.1.5
    - pyopengl-accelerate==3.1.5
    - pyparsing==3.1.1
    - pyro4==4.80
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytz==2021.1
    - pyyaml==6.0.1
    - pyzmq==23.1.0
    - qdldl==0.1.5.post2
    - regex==2023.10.3
    - requests==2.26.0
    - sacremoses==0.0.53
    - safetensors==0.4.0
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - scs==3.2.0
    - send2trash==1.8.0
    - sentry-sdk==1.34.0
    - serpent==1.40
    - setproctitle==1.3.3
    - setuptools==68.0.0
    - simple-term-menu==1.6.1
    - smmap==5.0.1
    - soupsieve==2.3.2.post1
    - stable-baselines3==1.2.0
    - statsmodels==0.13.2
    - svm==0.1.0
    - tenacity==8.0.1
    - termcolor==2.3.0
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tokenizers==0.10.3
    - torch==1.10.2
    - torchfile==0.1.0
    - tornado==6.1
    - tqdm==4.62.2
    - traitlets==5.2.2.post1
    - transformers==4.5.1
    - ttkbootstrap==1.5.1
    - typing==3.7.4.3
    - typing-extensions==4.7.1
    - urllib3==1.26.18
    - visdom==0.1.8.9
    - wandb==0.15.12
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - widgetsnbextension==3.6.0
    - wrapt==1.15.0
    - xmltodict==0.12.0
    - zipp==3.8.0

